### ISSUE TITLE
Make Property Pages to be a tab

### ISSUE THREAD

**Issue by NN---** [nuproj/nuproj#156]
A tab like a C#/VB project settings.
And not a modal window like a C++ project settings

**Comment by AArnott** [comment]
Trivia:
The Property Pages dialog is not modal. It is actually modeless.
The tab view is called the "project designer". 

NuProj is based on CPS, which doesn't yet offer a convenient way to offer project designer pages. We may do this sometime in the future, but won't fixing for now since short of a new feature in CPS, I don't think this will ever happen as it does not enable any new scenario and would be a great deal of work for the NuProj developers.

**Comment by NN---** [comment]
@AArnott I see.
It is very helpful when project consists of several packages.
Not a showstopper for sure, C++ projects still doesn't support it and we live with it :)

**Comment by AArnott** [comment]
Thanks for understanding.
Can you elaborate on how it is helpful when a project consists of several packages?

**Comment by NN---** [comment]
It is the same that you have in C# projects.
You can open them side-to-side then compare and copy-paste the needed settings.
Of course you can do it with a comparison tool but the tool must understand XML structure.

**Comment by AArnott** [comment]
I see. side-by-side view definitely isn't possible with the property pages dialog.
One thing the property pages dialog offers that the project designer does not though, may help you with your copy-paste requirement: the property pages dialog allows multi-selection. So you can select all your nuproj projects at once with the property pages dialog open, then set values that will then be mass-applied to all selected projects. So you can maintain the same settings across all projects without copy-pasting.

**Comment by NN---** [comment]
@AArnott Nice, didn't know about that.
