### ISSUE TITLE
Support project.json *within nuproj itself*

### ISSUE THREAD

**Issue by AArnott** [nuproj/nuproj#165]
You know, if we imported MS.Common.props and .targets, we could use project.json inside nuproj projects, which would be nice. 
Otherwise, can we do the same stuff that project.json support in these MSBuild files do, so we can add build authoring .props and .targets to our .nuproj project files using project.json?

**Comment by kovalikp** [comment]
> project.json support within the NuProj itself would allow us to manually create the project.json file (which is trivial) and add the dependency on Nerdbank.GitVersioning right there. The build would take it from there adding all the necessary imports. So lack of NuGet Client support for NuProj doesn't get in the way any more.

I don't think this is going to work. Here is what I found out:
- project.json support is provided via `MSBuild\Microsoft\NuGet\Microsoft.NuGet.targets` injected by `MSBuild\14.0\Microsoft.Common.Targets\ImportAfter\Microsoft.NuGet.ImportAfter.targets` (as I mentioned on gitter).
- `Microsoft.NuGet.targets` **requires** `project.lock.json` and `$(MSBuildProjectName).nuget.targets`
- `Microsoft.NuGet.targets` **ignores** `project.json`.
- The problem is, those two files are generated by Restore NuGet Packages operation.
- Which of course ignores NuProj, because NuGet does not support our project type.

So unless I missed something, I'm afraid we have to wait for NuGet team to provide first class support for CPS project.

**Comment by AArnott** [comment]
> Which of course ignores NuProj, because NuGet does not support our project type.

Which restore operation ignores NuProj? The one in VS or at the command line (or both)?

**Comment by kovalikp** [comment]
Only tested in VS at the time. Now I've tried command line and it indeed generates `project.lock.json` and `$(MSBuildProjectName).nuget.targets` files. Also `$(MSBuildProjectName).nuget.targets` gets imported into project out of the box.

I guess that's :+1:

**Comment by AArnott** [comment]
Yes, that's much better than what we don't have working today. :)
And getting the VS NuGet client to work with NuProj is within reach as well. Just a PR or two away.

**Comment by AArnott** [comment]
Fixed by c300461e6d4
