### ISSUE TITLE
allow a "LocalNuGet" environment variable that (if set) will be used for OutDir

### ISSUE THREAD

**Issue by zbrad** [nuproj/nuproj#220]
This is extremely useful during development of multiple packages.

**Comment by AArnott** [comment]
I agree this is useful. I have my own extension that copies nupkg files built from NuProj into a common directory that I then register in VS as a package source. Building that functionality into NuProj sounds good to me.

Note that I don't think we'd use the value as OutDir itself, since that would prevent it from being copied to the bin folder, where it ought to be. I think this feature should *copy* the file to the additional directory.

**Comment by zbrad** [comment]
My only additional thought on this is that having a nupkg in my bin folder isn't that useful to me, since it's not easily discoverable or reusable.   Always putting it into my local common place is useful.   

An additional variation would be to allow multiple expansions that also included ProjectNames, etc, that could allow a group of related projects to reuse a "local nuget" that was only for those related projects or solutions.

**Comment by zbrad** [comment]
Just FYI, for now I'm adding this to my nuproj templates:
  <PropertyGroup>
    <OutDir Condition="'$(LocalNuGet)' != ''">$(LocalNuGet)</OutDir>
  </PropertyGroup>

Since it's in the nuproj file, I can always further manipulate the name...

**Comment by AArnott** [comment]
I was just about to suggest you do that. I believe we'll need more folks converging on a single solution before we update NuProj itself to support it out of the box.
