### ISSUE TITLE
Library Support & Documentation

### ISSUE THREAD

**Issue by AlexEyler** [nuproj/nuproj#237]
Documentation on the website http://nuproj.net/documentation/#packaging-files and the README file use the following syntax:
```
<ItemGroup>
  <Library Include="$(BasePath)HelloWorld.dll" />
    <TargetFramework>net40</TargetFramework>
  </Library>
</ItemGroup>
```

However, this syntax no longer works in the latest version of NuProj (0.10.4-beta). Either the documentation should be updated or support should be re-enabled for the Library tag.

Related: what is the proper syntax for this, now? This?
```
<ItemGroup>
  <Content Include="$(BasePath)HelloWorld.dll">
    <Link>lib/net40</Link>
  </Content>
  <Reference Include="HelloWorld.dll" /> <!-- should this be lib/net40/HelloWorld.dll? -->
</ItemGroup>
```

**Comment by AArnott** [comment]
0.10.4-beta is very old. The latest is 0.10.48-beta-gea4a31bbc5, but it's only available on the https://www.myget.org/F/aarnott/api/v3/index.json feed so you have to add it to your nuget.config file. I would highly recommend you use the latest version.

Rather than use `Library` or `Content`, I recommend using project and assembly references. NuProj will automatically place the assembly outputs into the right folders.

The documentation is also probably rather old. I'm not sure I have access to update that.

**Comment by AArnott** [comment]
CC: @terrajobst

**Comment by AlexEyler** [comment]
Thanks Andrew, I'll switch to that version and  start using assembly references.
