### ISSUE TITLE
NuProj ProjectRefrences are getting "rebuilt"

### ISSUE THREAD

**Issue by samswork** [nuproj/nuproj#255]
I'm seeing a behavior where CSPROJ files are built twice in my repository. I did some digging and the second build comes from the .nuproj ProjectReference. For reasons I don't yet fully understand, this seems to re-build the CSPROJ files.
I've noticed I can mitigate the issue by adding ReferenceOutputAssembly = false in the reference. But I rather like the automatic reference behavior and I'd like to keep it.
Has anyone else seen this issue? Any ideas how to fix?

**Comment by AArnott** [comment]
We've seen this before, and have tests now to verify it doesn't happen. But maybe we missed something.
Just to be sure though, what version of NuProj are you using?

**Comment by samswork** [comment]
I'm currently using 0.9.2.0. I see now this isn't the latest. Is the fix in this build?

**Comment by kovalikp** [comment]
Yes, multiple rebuilds have been resolved some time ago. Just FYI, multiple rebuilds are generally caused by passing different properties to `MSBuild` task, therefore it's important to use only `Properties="%(ProjectReference.SetConfiguration); %(ProjectReference.SetPlatform)"` when you try build project references.

**Comment by AArnott** [comment]
I'll close then since you were on an old build. Please let us know if it repros with the latest version.
