### ISSUE TITLE
The project type is not supported by this installation

### ISSUE THREAD

**Issue by peterM** [nuproj/nuproj#279]
Hello.

I have installed latest version of NuProj. 
Every time I try add NuGet Project to my Solution I get this error.
I also tries reinstall , repair installation. All time wit no success.
![capture](https://cloud.githubusercontent.com/assets/2149830/22640164/ba8dffd2-ec51-11e6-8962-a09dfc881272.PNG)

Thanks
Peter

**Comment by AArnott** [comment]
What version of Visual Studio are you using?

**Comment by peterM** [comment]
VS 2015 U3

**Comment by kovalikp** [comment]
Could you try to clean VS MEF cache? I't located in `%localappdata%\Microsoft\VisualStudio\14.0\ComponentModelCache`. Also if you're using NuGet packages for build integration, can you update them too?

**Comment by peterM** [comment]
Corrupted was MEF cache :) ... thanks
You can close

**Comment by TheFrogPrince** [comment]
This did the trick for me.  The problem presented itself when I uninstalled NuProj and then reinstalled it (because I couldn't add any project items to the NuProj project).  Upon reinstall, I would get this error.   Also... by clean, it's worth noting that Kovalikp means to go ahead and delete the ComponentModelCache folder.  It will be rebuild the folder the next time you start Visual Studio.
