### ISSUE TITLE
NuProj for VS 2017 not compatible with Mac VS 2017 .nuproj?

### ISSUE THREAD

**Issue by eli-darkly** [nuproj/nuproj#304]
Mac Visual Studio apparently supports NuGet package projects out of the box. However, when I opened a solution in Windows that I had created on a Mac, the `.nuproj` project was shown as "(incompatible) - The application is not installed." Similarly, when I created a NuGet project on Windows, it was shown as invalid on the Mac.

Are these project types supposed to be interoperable? If not, is there any way I can hack it to work on both platforms by conditionally including different targets?

**Comment by romanogolikhin** [comment]
I have the same problem.

**Comment by AArnott** [comment]
If VS for Mac supports a .nuproj project type, it's completely unrelated to this project. I had heard that some other folks had reused project file extension for their own use. That might be what this is. They didn't go to any effort to make them interoperable. And at this point, this project is on ice since .NET SDK projects make packages so easy to build.
